language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"

install:
    - pip install --use-mirrors tox coveralls

script:
    - tox -e py${TRAVIS_PYTHON_VERSION//./}

after_success:
    - coveralls
