language: python
python:
    - "2.7"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py33
    - TOX_ENV=py34

install:
    - pip install --use-mirrors tox coveralls

script:
    # install python 3.4
    - "[[ ${TOX_ENV} == py34 ]] || [[ ${TOX_ENV} == docs-code-python34 ]] && sudo add-apt-repository -y ppa:fkrull/deadsnakes || true"
    - "[[ ${TOX_ENV} == py34 ]] || [[ ${TOX_ENV} == docs-code-python34 ]] && sudo apt-get -y update && sudo apt-get -y install python3.4 || true
    - tox -e $TOX_ENV

after_success:
    - coveralls
